# CMake generated Testfile for 
# Source directory: E:/PhysiK
# Build directory: E:/PhysiK/build-mkl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[PhysiKTests]=] "E:/PhysiK/build-mkl/Debug/PhysiKTests.exe")
  set_tests_properties([=[PhysiKTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;297;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[PhysiKTests]=] "E:/PhysiK/build-mkl/Release/PhysiKTests.exe")
  set_tests_properties([=[PhysiKTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;297;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[PhysiKTests]=] "E:/PhysiK/build-mkl/MinSizeRel/PhysiKTests.exe")
  set_tests_properties([=[PhysiKTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;297;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[PhysiKTests]=] "E:/PhysiK/build-mkl/RelWithDebInfo/PhysiKTests.exe")
  set_tests_properties([=[PhysiKTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;297;add_test;E:/PhysiK/CMakeLists.txt;0;")
else()
  add_test([=[PhysiKTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[PhysiKMKLTests]=] "E:/PhysiK/build-mkl/Debug/PhysiKMKLTests.exe")
  set_tests_properties([=[PhysiKMKLTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;315;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[PhysiKMKLTests]=] "E:/PhysiK/build-mkl/Release/PhysiKMKLTests.exe")
  set_tests_properties([=[PhysiKMKLTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;315;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[PhysiKMKLTests]=] "E:/PhysiK/build-mkl/MinSizeRel/PhysiKMKLTests.exe")
  set_tests_properties([=[PhysiKMKLTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;315;add_test;E:/PhysiK/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[PhysiKMKLTests]=] "E:/PhysiK/build-mkl/RelWithDebInfo/PhysiKMKLTests.exe")
  set_tests_properties([=[PhysiKMKLTests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/PhysiK/CMakeLists.txt;315;add_test;E:/PhysiK/CMakeLists.txt;0;")
else()
  add_test([=[PhysiKMKLTests]=] NOT_AVAILABLE)
endif()
